services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: frontend-container
    volumes:
      - ./frontend:/var/www/frontend
      - /var/www/frontend/node_modules
    ports:
      - 8000:8000
    restart: unless-stopped
